name: Build and Release

on:
  push:
    tags: [ "v*.*.*" ]

env:
  BUILD_CONFIGURATION: Release_MT
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
          doNotCache: false

    - name: Build
      working-directory: ${{ github.workspace }}
      run: |
        vcpkg integrate install
        msbuild /m "/p:Configuration=${{ env.BUILD_CONFIGURATION }};Platform=x64" .
        msbuild /m "/p:Configuration=${{ env.BUILD_CONFIGURATION }};Platform=x86" .

    - name: Compression
      run: |
        7z a -tzip -mx9 ./x64/Release_MT/im01_x86_64.zip ./x64/Release_MT/im01.exe
        7z a -tzip -mx9 ./Win32/Release_MT/im01_x86.zip ./Win32/Release_MT/im01.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./x64/Release_MT/im01_x86_64.zip
          ./Win32/Release_MT/im01_x86.zip